version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./documentation/src:/app/src
      - ./documentation/website/blog:/app/website/blog
      - ./documentation/website/core:/app/website/core
      - ./documentation/website/i18n:/app/website/i18n
      - ./documentation/website/pages:/app/website/pages
      - ./documentation/website/static:/app/website/static
      - ./documentation/website/sidebars.json:/app/website/sidebars.json
      - ./documentation/website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
